name: Build and Push Docker Images to Google Artifact Registry

on:
  push:
    branches:
      - main

jobs:
  docker-build-push:
    name: Build & Push Docker Images
    runs-on: ubuntu-latest

    env:
      PROJECT_ID: your-gcp-project-id
      REGION: us-central1
      REPO_NAME: your-artifact-repo-name

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker credentials for Google Artifact Registry
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker $REGION-docker.pkg.dev --quiet

      ##############################
      # Build & Push: React (FE)
      ##############################
      - name: Build and Push FE Docker Image
        run: |
          docker build -t $REGION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/frontend:latest ./FE
          docker push $REGION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/frontend:latest

      ##############################
      # Build & Push: API1 (FastAPI)
      ##############################
      - name: Build and Push API1 Docker Image
        run: |
          docker build -t $REGION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/api1:latest ./BE/API1
          docker push $REGION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/api1:latest

      ##############################
      # Build & Push: API2 (Node.js)
      ##############################
      - name: Build and Push API2 Docker Image
        run: |
          docker build -t $REGION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/api2:latest ./BE/API2
          docker push $REGION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/api2:latest
